### ISSUE TITLE
In GraphQL data modeling, you should think of your data as a graph, not as tables

### ISSUE THREAD

**Issue by duongphuhiep** [Shopify/graphql-design-tutorial#43]
It means that your data is a bunch of Nodes and Edges, not a bunch of table or column..

> Since the product-to-collection relationship is many-to-many, you've got a join table in the middle called CollectionMembership

You should be able to design the a Many-to-Many relationship in your schema without the `CollectionMembership` things

**Comment by swalkinshaw** [comment]
I don't think I understand the issue or what improvement you're suggesting.

The tutorial starts with an example of how a schema would look if you directly represented your database structure and then shows how to improve it, which removes the need for `CollectionMembership` exactly as you say. See https://github.com/Shopify/graphql-design-tutorial/blob/master/TUTORIAL.md#representing-collectionmemberships
