### ISSUE TITLE
When designing GraphQL, you should think of your data as a Graph instead of Tables

### ISSUE THREAD

**Issue by duongphuhiep** [Shopify/graphql-design-tutorial#56]
"Since the product-to-collection relationship is many-to-many, you've got a join table in the middle called CollectionMembership."

It feels like Authors still think about the traditional tables and columns when designing a GraphQL model. As a result, we got a "table" with 2 "columns" like this... in a GraphQL data model.

```
type CollectionMembership {
  collectionId: ID!
  productId: ID!
}
```

IMO, It is not the right mind to brain storming a GraphQL, you have to treat your data as a Graph, so think about them in term "nodes" and "edges" instead of "table" and "column".

By consequence, the relationship between Product & Collection should be designed as following:

```
type Product {
  id: ID!
  name: String!
  # Other product related fields...
  collections: ProductCollectionConnection!
}

type Collection {
  id: ID!
  name: String!
  # Other collection related fields...
  products: CollectionProductConnection!
}

type ProductCollectionConnection {
  edges: [ProductCollectionEdge!]!  # Non-null list of edges
  pageInfo: PageInfo!  # Information for pagination (optional)
}

type CollectionProductConnection {
  edges: [CollectionProductEdge!]!  # Non-null list of edges
  pageInfo: PageInfo!  # Information for pagination (optional)
}

type ProductCollectionEdge {
  node: Collection!  # Collection this edge points to
  # Optional fields specific to the product-collection relationship (e.g., position)
}

type CollectionProductEdge {
  node: Product!  # Product this edge points to
  # Optional fields specific to the collection-product relationship
}
```

With this schema, you can write GraphQL queries to fetch products with their collections and vice versa. Here's an example:

```
{
  product(id: 1) {
    name
    collections {
      edges {
        node {
          name
        }
      }
    }
  }
}
```

In my example is a 2-directions relationship, Product->Collection & Collection->Product, you can remove one direction if it is not interessting to keep..

**Comment by ravangen** [comment]
👋 Thanks for the feedback. Is there a specific portion you would like to see changed?

> "Since the product-to-collection relationship is many-to-many, you've got a join table in the middle called CollectionMembership."

> It feels like Authors still think about the traditional tables and columns when designing a GraphQL model. As a result, we got a "table" with 2 "columns" like this... in a GraphQL data model.

The tutorial's style is more about evolution of an implementation, with the first section highlighting what might be done at first and how it [could change into a "better" approach](https://github.com/Shopify/graphql-design-tutorial/blob/master/TUTORIAL.md#representing-collectionmemberships). Agreed that the table is an implementation detail of persistence that does not need to be represented in the graph.

> ```graphql
> type Product {
>    collections: ProductCollectionConnection!
> }
> ```

This tutorial was based around the GraphQL Ruby implementation ([docs](https://graphql-ruby.org/pagination/connection_concepts.html)), which by _default_ does not include the originating type name in the connection type name. You end up with `collections: CollectionConnection!` and `CollectionEdge` where multiple connection fields can reuse the same connection type when targeting the same `Collection` type. I wish this wasn't the case, but alas I mention it as an FYI to explain the tutorials naming.

> With this schema, you can write GraphQL queries to fetch products with their collections and vice versa. 

The tutorial doesn't provide the `Product` fields, but being bidirectional makes sense (and what Shopify does).
