### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by chih-chen** [Shopify/graphql-design-tutorial#8]
Hi everyone! 

First of all, thanks for this awesome tutorial, it is really helpful. 

I have a question about interfaces. In [this](https://github.com/Shopify/graphql-design-tutorial/blob/master/TUTORIAL.md#representing-collections) section states that `AutomaticCollection` and `ManualCollection` are actually implementation detail which could be transparent for the client.

I see that for a `ManualCollection`, make sense that it has empty `CollectionRule`, so not a big deal breaker. But imagine if one day it is necessary to add new fields which is `ManualCollection` specific. 

My thoughts: 
- I could keep the `type Collection`, and add `manualCollectionFieldSet` to include all these `ManualCollection` specific fields. Like this: 
```
type Collection {
    ...
    manualCollectionFiledSet: ManualCollectionFieldSet
}

type ManualCollectionFieldSet {
    ...
    // manual collection specific fields
}
```
But for this solution, the response may contain a lot of null values. 

- I could create an interface and have different implementations. I personally prefer this solution because the result is cleaner and the schema don't need a lot of null type fields. 
 ```
interface Collection {
    ...
}

type ManualCollectionFieldSet implements Collection {
    ...
    // manual collection specific fields
}
```
I'm a bit confused because I'm facing a similar situation. Isn't it a better option to have an interface for `Collection` and two different implementations? It would be also easier to plug a new `Collection` type. What are your experiences working with interfaces? Is there any caveat I not aware of?  

Thanks a lot!

**Comment by swalkinshaw** [comment]
Great questions.

> But imagine if one day it is necessary to add new fields which is ManualCollection specific.

The solution depends on how generic you can make these fields in my opinion. As you mentioned, `CollectionRule` was made more generic and the empty list is a fine trade-off which still makes some semantic sense.

A decision like this is more of a spectrum, not really a simple binary choice. In our case (and the tutorial's), there aren't enough reasons to use an interface. But if you start adding more differences, then maybe an interface does make more sense. In the end it's your API and up to you anyway 😄

**Comment by chih-chen** [comment]
> The solution depends on how generic you can make these fields in my opinion.

Great point! I believe that `ManualCollectionFiledSet` is a generic field, if it is null, it means that these fields are not applicable for a `AutomaticCollection`, so still have some semantic meaning. It also follows the rule 6:

> Rule 6: Group closely-related fields together into subobjects.

So I followed this principle, but I don't know if it is a good practice. 
Because, imagine if there are 10 types of collection, and each type has a set of specific fields, I would like to query all these specific fields. In this case, what I need to do is. 
```
query {
    category {
        ...
        fieldSet1
fieldSet1
fieldSet1
    }
}

**Comment by eapache** [comment]
Another solution (and one that we use internally in a few places - we should find a way to work it into the tutorial somehow) is to use a union on the differing fields. Something like:
```
type Collection {
    ...
    specificFieldSet: SpecificFieldSet!
}

union SpecificFieldSet = CustomCollectionFields | Collection2Fields | Collection3Fields
```

The advantage of this is that often you can find a better semantic name than `SpecificFieldSet`. For example, say that the collections were different specifically in how products were sorted (and these specific field sets implemented different approaches to that). Then you could call the field and union `productSortDetails: ProductSortDetails!`  and it's much more obvious what it does and why.

**Comment by chih-chen** [comment]
Nice point! 
I believe that for my situation, some specialization is required. So I will go with interfaces or unions. 
There are some awesome articles talking about these topics: 
- [GraphQL Interface and Unions -  how to design GraphQL schema](https://medium.com/graphql-mastery/graphql-interfaces-and-unions-how-to-design-graphql-schema-834e025a4544)
- [GraphQL tour: Interfaces and unions](https://medium.com/the-graphqlhub/graphql-tour-interfaces-and-unions-7dd5be35de0d)

Maybe these tips could be added to the tutorial somehow. 
Thanks for the discussion, it was really helpful and constructive! Closing this issue.
